version: '3.8'

services:
  frontend:
    image: signalen/frontend:latest
    volumes:
      - ./app.json:/app.json
    ports:
      - 3001:80
    depends_on:
      - backend

  backend:
    image: signalen/backend:latest
    environment:
      - ALLOWED_HOSTS=localhost
      - ALWAYS_OK=True
      - API_FILTER_EXTRA_PROPERTIES=False
      - API_VALIDATE_SOURCE_AGAINST_SOURCE_MODEL=False
      - AUTOMATICALLY_CREATE_CHILD_SIGNALS_PER_CONTAINER=True
      - DATABASE_HOST_OVERRIDE=database
      - DATABASE_PORT_OVERRIDE=5432
      - DB_NAME=signals
      - DB_PASSWORD=insecure
      - DJANGO_SETTINGS_MODULE=signals.settings.testing
      - ELASTICSEARCH_HOST=localhost:8000
      - ELASTICSEARCH_INDEX=unknown
      - FRONTEND_URL=http://localhost:3001
      - INITIALIZE_WITH_DUMMY_DATA=1
      - SECRET_KEY=insecure
    command:
      - /initialize-backend.sh
    volumes:
      - ./initialize-backend.sh:/initialize-backend.sh
    ports:
      - 8000:8000
    depends_on:
      - database
      - dex

  database:
    image: amsterdam/postgres11:latest
    environment:
      POSTGRES_DB: signals
      POSTGRES_USER: signals
      POSTGRES_PASSWORD: insecure
    ports:
      - 5432:5432

  dex:
    image: quay.io/dexidp/dex:v2.23.0
    user: root
    command: serve /config.yml
    ports:
      - 5556:5556
    volumes:
      - ./dex.yml:/config.yml
      - dex-data:/data

volumes:
  dex-data: